FROM centos:8

RUN mkdir -p /minio/root
WORKDIR /root

ENV MINIO_ACCESS_KEY=minioaccesskey
ENV MINIO_SECRET_KEY=miniosecretkey
ENV MINIO_PROMETHEUS_AUTH_TYPE=public

RUN curl --output minio https://dl.min.io/server/minio/release/linux-amd64/archive/minio.RELEASE.2021-01-16T02-19-44Z && \
    chmod +x minio

CMD ./minio server ${servers}